pipelines:
  branches:
    devops:
      - step:
          name: Building the app
          image: node:20.17.0
          script:
            - apt-get update && apt-get install -y awscli
            # Install GPG
            #- apt-get -y install gnupg
            #- gpg --quiet --batch --yes --decrypt --passphrase=$GPG_PASSPHRASE --output .env .env-staging.gpg
            - yarn install
            - yarn run build
          artifacts:
            - dist/**
      - step:
          name: Deploying the app to S3
          deployment: Staging
          script:
            - pipe: atlassian/aws-s3-deploy:0.2.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $S3_BUCKET
                ACL: "public-read"
                CACHE_CONTROL: "no-cache,no-store,must-revalidate"
                LOCAL_PATH: "dist/"
