import type { ThemeConfig } from "antd";
import { theme as antdTheme } from "antd";

export const getThemeConfig = (currentPrimaryColor: string): ThemeConfig => ({
  algorithm: antdTheme.defaultAlgorithm,
  token: {
    colorPrimary: currentPrimaryColor,
    colorBgContainer: "#ffffff",
    colorText: "#0c0d0d",
    colorTextSecondary: "#A1A1AA",
    borderRadius: 10,
    wireframe: false,
    colorBgElevated: "#ffffff",
    colorBorder: "#374151",
    fontSize: 16,
    controlHeight: 46,
    fontFamily: "Satoshi",
    fontFamilyCode: "Satoshi",
  },

  components: {
    Typography: {
      fontFamily: "Satoshi",
      fontFamilyCode: "Satoshi",
      fontSizeHeading3: 20,
      colorTextHeading: currentPrimaryColor,
      fontWeightStrong: 700,
      titleMarginTop: 0,
      titleMarginBottom: 16,
    },
    Button: {
      colorPrimary: currentPrimaryColor,
      algorithm: true,
      borderRadius: 10,
      borderRadiusLG: 10,
      borderRadiusSM: 10,
      borderRadiusXS: 10,
      controlHeight: 46,
      primaryColor: "#ffffff",
      colorText: "#FFFFFF",
      fontFamily: "Satoshi",
    },
    Input: {
      colorBgContainer: "#ffffff",
      colorError: "#EF4444",
      colorErrorBg: "#fff4f4",
      colorErrorBorder: "#EF4444",
      colorErrorBgHover: "#EF4444",
      colorTextPlaceholder: "#888E91",
      colorBorder: "#EAEBEB",
      colorText: "#000000",
      activeBorderColor: currentPrimaryColor,
      hoverBorderColor: currentPrimaryColor,
      activeShadow: "0 0 0 0px rgba(124, 58, 237, 0.2)",
      errorActiveShadow: "0 0 0 0px rgba(255, 77, 79, 0.2)",
      borderRadius: 10,
      borderRadiusLG: 10,
      borderRadiusSM: 10,
      borderRadiusXS: 10,
      controlHeight: 46,
      fontFamily: "Satoshi",
      colorIcon: "#9C9C9C",
    },
    Upload: {
      colorPrimary: currentPrimaryColor,
      borderRadius: 10,
      borderRadiusLG: 10,
      borderRadiusSM: 10,
      borderRadiusXS: 10,
      controlHeight: 46,
      fontFamily: "Satoshi",
    },
    Radio: {
      colorPrimary: currentPrimaryColor,
      buttonSolidCheckedBg: currentPrimaryColor,
      buttonCheckedBg: "rgba(61, 194, 178, 0.05)",
      colorText: "#d9d9d9",
      colorBorder: "#d9d9d9",
      borderRadius: 10,
      fontSize: 16,
      borderRadiusLG: 10,
      borderRadiusSM: 10,
      borderRadiusXS: 10,
      controlHeight: 40,
      fontFamily: "Satoshi",
    },
    Form: {
      labelColor: "#0C0D0D",
      labelRequiredMarkColor: "#3dc2b2",
      fontFamily: "Satoshi",
      itemMarginBottom: 16,
    },
    Select: {
      colorBgContainer: "ffffff",
      colorBorder: "#EAEBEB",
      activeBorderColor: currentPrimaryColor,
      optionSelectedBg: "#ffffff",
      selectorBg: "#ffffff",
      borderRadius: 10,
      borderRadiusXS: 10,
      borderRadiusSM: 10,
      controlHeight: 46,
      colorIcon: "#ffffff",
      fontFamily: "Satoshi",
      colorTextPlaceholder: "#888E91",
    },

    Menu: {
      colorItemBg: "transparent",
      colorItemText: "#6E7477",
      colorItemTextSelected: "#ffffff",
      colorItemBgSelected: currentPrimaryColor,
      itemActiveBg: currentPrimaryColor,
      fontFamily: "Satoshi",
      subMenuItemSelectedColor: currentPrimaryColor,
    },
    Divider: {
      colorSplit: "#667085",
      colorText: "#667085",
      colorTextHeading: "#667085",
      lineWidth: 0.5,
    },
    Card: {
      colorBgContainer: "#1F2937",
      borderRadius: 12,
      fontFamily: "Satoshi",
    },
    Table: {
      colorBgContainer: "transparent",
      colorText: "#0c0d0d",
      colorTextHeading: "#0c0d0d",
      borderRadius: 8,
      rowHoverBg: "#F9FAFB",
      fontSize: 14,
      fontFamily: "Satoshi",
    },
    Layout: {
      colorBgContainer: "#ffffff",
      siderBg: "#ffffff",
    },
    Checkbox: {
      colorPrimary: "#7D17FE",
    },
    Modal: {
      borderRadius: 12,
      colorBgElevated: "#1F2937",
      fontFamily: "Satoshi",
    },
    DatePicker: {
      colorBorder: "#EAEBEB",
      borderRadius: 10,
      borderRadiusXS: 10,
      borderRadiusSM: 10,
    },
    Tag: {
      colorBorder: "none",
      borderRadiusSM: 10,
    },
    Switch: {
      colorPrimary: currentPrimaryColor,
    },
    Tabs: {
      colorBgContainer: currentPrimaryColor,
      colorFillAlter: "#fafafa",
      controlHeight: 42,
      controlHeightLG: 42,
    },
    Progress: {
      defaultColor: currentPrimaryColor,
      colorText: "#0C0D0D",
      fontSize: 16,
    },
  },
});
